import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:nuriva/core/config/app_config.dart';
import 'package:nuriva/core/di/providers.dart';
import 'package:nuriva/core/logging/app_logger.dart';
import 'package:nuriva/firebase_options.dart';

/// Starts the application with error handling and DI in place.
///
/// Everything that must happen before the first frame lives here, so `main.dart`
/// stays a one-liner and the startup sequence is testable and greppable.
Future<void> bootstrap(Widget Function() appBuilder) async {
  final config = AppConfig.fromEnvironment();
  final logger = AppLogger(
    config: config,
    sink: config.logLevel == LogLevel.none
        ? const NullLogSink()
        : const ConsoleLogSink(),
  );

  await runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();

      // Framework-level errors (build, layout, paint).
      FlutterError.onError = (details) {
        logger.error(
          'Flutter framework error',
          context: {'library': details.library ?? 'unknown'},
          cause: details.exception,
          stackTrace: details.stack,
        );
        if (config.allowDeveloperTools) {
          FlutterError.presentError(details);
        }
      };

      // Errors from the engine that never reach the framework.
      PlatformDispatcher.instance.onError = (error, stack) {
        logger.error(
          'Uncaught platform error',
          cause: error,
          stackTrace: stack,
        );
        return true;
      };

      await initializeBackend(config, logger);

      logger.info('Starting NURIVA', context: {
        'flavor': config.flavor.name,
        'horizonDays': config.doseHorizonDays,
      });

      runApp(
        ProviderScope(
          overrides: [
            appConfigProvider.overrideWithValue(config),
          ],
          child: appBuilder(),
        ),
      );
    },
    (error, stack) {
      // Anything that escaped both handlers above.
      logger.error('Unhandled zone error', cause: error, stackTrace: stack);
    },
  );
}

/// Backend initialization seam.
///
/// Firebase project `nuriva-27e59` was created with Firestore and Storage
/// pinned to `asia-south1` (India DPDP Act 2023 — see
/// `docs/NURIVA_MODULE_STATUS.md`). `firebase_options.dart` was generated by
/// `flutterfire configure` and is safe to commit (it holds public client
/// identifiers, not secrets — access is enforced by Firestore/Storage rules
/// and App Check, not by hiding this file).
///
/// App Check is deferred to Module 17 (Security), which is where the rest of
/// the hardening work lives; wiring it in isolation now would be security
/// theatre without the rules and attestation that go with it.
@visibleForTesting
Future<void> initializeBackend(AppConfig config, AppLogger logger) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  logger.info('Firebase initialized', context: {'projectId': 'nuriva-27e59'});
}
